[book]
multilingual = false
src = "src"
title = "Localization at Mozilla - Internal Documentation"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/mozilla-l10n/documentation/"
edit-url-template = "https://github.com/mozilla-l10n/documentation/edit/main/{path}"
no-section-label = true
